"""empty message

Revision ID: 3520dc9e8848
Revises: dfbf262ac823
Create Date: 2026-03-23 18:28:24.065792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3520dc9e8848'
down_revision: Union[str, Sequence[str], None] = 'dfbf262ac823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('test_2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'test_2')
    # ### end Alembic commands ###
