"""empty message

Revision ID: cd0aa7baa7b5
Revises: 3520dc9e8848
Create Date: 2026-03-23 18:29:25.489270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0aa7baa7b5'
down_revision: Union[str, Sequence[str], None] = '3520dc9e8848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'test_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('test_2', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
